name: Test Projet

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Télécharger code
        uses: actions/checkout@v3

      - name: Installer Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installer frontend
        run: npm install

      - name: Build frontend
        run: npm run build || echo "No build"

      - name: Installer backend
        run: |
          cd rh-backend
          npm install

      - name: Tester backend
        run: |
          cd rh-backend
          echo "Backend OK"